### ISSUE TITLE
Making methodology more transparent

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/flip-my-lawn#6]
After demo-ing FlipMyLawn.com to the Civic Spark Fellows, it seemed worthwhile to link the methodology doc also in the actual estimates section to make that more clear. People might not go back up to the "what is..." section. Thinking it'd be good to add the text below in italics:

"Based on cost estimates of water, installation (considering rebates), and yard maintenance" _(Methodology LINK -- remember these estimates may be optimistic)_

Also FYI I changed the Methodology to say v1.1 rather than draft.

**Comment by dmarulli** [comment]
addressed with #9
