### ISSUE TITLE
Integration with CalScape

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/flip-my-lawn#7]
Would be super cool if FlipMyLawn.com had the Calscape functionality enabling people to see California plants native to their specific region. 

https://calscape.org/

**Comment by patwater** [comment]
@dmarulli a good research project is to figure out if we can just pull the data directly by scraping the CalScape website: https://calscape.org/loc-34.0958,-118.1868(4210%20via%20arbolada)/?&poploc=1

**Comment by patwater** [comment]
@dmarulli PA proposal 

TAB NAME: "Go Local!"

BUTTON: "Find California plants native to your area"

**Comment by dmarulli** [comment]
addressed with #10
